X = "Hello World"
X = 20
X = 20.5
X = ["apple", "banana", "cherry"]
X = ("apple", "banana", "cherry")
X = {"name": "onthich", "age":20}
X = {"apple", "banana", "cherry"}
X = frozenset({"apple", "banana", "cherry"})
X = True
X = b"hello"